create table T_STT_SETTLE_PERIOD
(
  PERIOD_ID      NUMERIC(10) not null,
  SETTLE_TYPE_ID VARCHAR(2) not null,
  SETTLE_PERIOD  NUMERIC(7,1) not null,
  CONSTRAINT T_STT_SETTLE_PERIOD_PK PRIMARY KEY(PERIOD_ID)
);
create table T_STT_SETTLE_SCHEME
(
  SCHEME_ID      NUMERIC(10) not null,
  SCHEME_NAME    VARCHAR(100) not null,
  TRS_CODE       VARCHAR(8) not null,
  SETTLE_TYPE_ID VARCHAR(2) not null,
  SETTLE_PERIOD  NUMERIC(7,1) not null,
  WORK_FLAG      VARCHAR(3),
  STAT           CHAR(2) not null,
  AUDIT_ID       VARCHAR(128),
  AUDIT_DATE     DATE,
  MEMO           VARCHAR(256),
  CONSTRAINT T_STT_SETTLE_SCHEME_PK PRIMARY KEY(SCHEME_ID)
);
create table T_STT_SCHEME_ATTACH
(
  ATTACH_ID  NUMERIC(10) not null,
  MAIN_ID    VARCHAR(64) not null,
  MAIN_TYPE  VARCHAR(15) not null,
  SCHEME_ID  NUMERIC(10) not null,
  EFF_DATE   DATE not null,
  EXP_DATE   DATE,
  STAT       CHAR(2) not null,
  AUTHOR_ID  VARCHAR(128),
  AUDIT_ID   VARCHAR(128),
  AUDIT_DATE DATE,
  MEMO       VARCHAR(256),
  ACTUAL_DATE DATE
)
